//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicMvcApp.PrismaWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Building", Namespace="http://schemas.datacontract.org/2004/07/TwoToWin.Prisma.BasicWCFService.Entities")]
    [System.SerializableAttribute()]
    public partial class Building : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingCode {
            get {
                return this.BuildingCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingCodeField, value) != true)) {
                    this.BuildingCodeField = value;
                    this.RaisePropertyChanged("BuildingCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Floor", Namespace="http://schemas.datacontract.org/2004/07/TwoToWin.Prisma.BasicWCFService.Entities")]
    [System.SerializableAttribute()]
    public partial class Floor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FloorCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingCode {
            get {
                return this.BuildingCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingCodeField, value) != true)) {
                    this.BuildingCodeField = value;
                    this.RaisePropertyChanged("BuildingCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FloorCode {
            get {
                return this.FloorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorCodeField, value) != true)) {
                    this.FloorCodeField = value;
                    this.RaisePropertyChanged("FloorCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Room", Namespace="http://schemas.datacontract.org/2004/07/TwoToWin.Prisma.BasicWCFService.Entities")]
    [System.SerializableAttribute()]
    public partial class Room : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomCode {
            get {
                return this.RoomCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomCodeField, value) != true)) {
                    this.RoomCodeField = value;
                    this.RaisePropertyChanged("RoomCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionEntity", Namespace="http://schemas.datacontract.org/2004/07/TwoToWin.Prisma.BasicWCFService.Entities")]
    [System.SerializableAttribute()]
    public partial class ActionEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionCode {
            get {
                return this.ActionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionCodeField, value) != true)) {
                    this.ActionCodeField = value;
                    this.RaisePropertyChanged("ActionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrismaWCF.IPrismaService")]
    public interface IPrismaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrismaService/GetAllBuildings", ReplyAction="http://tempuri.org/IPrismaService/GetAllBuildingsResponse")]
        BasicMvcApp.PrismaWCF.Building[] GetAllBuildings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrismaService/GetAllBuildings", ReplyAction="http://tempuri.org/IPrismaService/GetAllBuildingsResponse")]
        System.Threading.Tasks.Task<BasicMvcApp.PrismaWCF.Building[]> GetAllBuildingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrismaService/GetFloors", ReplyAction="http://tempuri.org/IPrismaService/GetFloorsResponse")]
        BasicMvcApp.PrismaWCF.Floor[] GetFloors(string buildingCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrismaService/GetFloors", ReplyAction="http://tempuri.org/IPrismaService/GetFloorsResponse")]
        System.Threading.Tasks.Task<BasicMvcApp.PrismaWCF.Floor[]> GetFloorsAsync(string buildingCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrismaService/GetRooms", ReplyAction="http://tempuri.org/IPrismaService/GetRoomsResponse")]
        BasicMvcApp.PrismaWCF.Room[] GetRooms(string buildingCode, string floorCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrismaService/GetRooms", ReplyAction="http://tempuri.org/IPrismaService/GetRoomsResponse")]
        System.Threading.Tasks.Task<BasicMvcApp.PrismaWCF.Room[]> GetRoomsAsync(string buildingCode, string floorCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrismaService/GetAllWORequestActions", ReplyAction="http://tempuri.org/IPrismaService/GetAllWORequestActionsResponse")]
        BasicMvcApp.PrismaWCF.ActionEntity[] GetAllWORequestActions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrismaService/GetAllWORequestActions", ReplyAction="http://tempuri.org/IPrismaService/GetAllWORequestActionsResponse")]
        System.Threading.Tasks.Task<BasicMvcApp.PrismaWCF.ActionEntity[]> GetAllWORequestActionsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrismaServiceChannel : BasicMvcApp.PrismaWCF.IPrismaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrismaServiceClient : System.ServiceModel.ClientBase<BasicMvcApp.PrismaWCF.IPrismaService>, BasicMvcApp.PrismaWCF.IPrismaService {
        
        public PrismaServiceClient() {
        }
        
        public PrismaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrismaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrismaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrismaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BasicMvcApp.PrismaWCF.Building[] GetAllBuildings() {
            return base.Channel.GetAllBuildings();
        }
        
        public System.Threading.Tasks.Task<BasicMvcApp.PrismaWCF.Building[]> GetAllBuildingsAsync() {
            return base.Channel.GetAllBuildingsAsync();
        }
        
        public BasicMvcApp.PrismaWCF.Floor[] GetFloors(string buildingCode) {
            return base.Channel.GetFloors(buildingCode);
        }
        
        public System.Threading.Tasks.Task<BasicMvcApp.PrismaWCF.Floor[]> GetFloorsAsync(string buildingCode) {
            return base.Channel.GetFloorsAsync(buildingCode);
        }
        
        public BasicMvcApp.PrismaWCF.Room[] GetRooms(string buildingCode, string floorCode) {
            return base.Channel.GetRooms(buildingCode, floorCode);
        }
        
        public System.Threading.Tasks.Task<BasicMvcApp.PrismaWCF.Room[]> GetRoomsAsync(string buildingCode, string floorCode) {
            return base.Channel.GetRoomsAsync(buildingCode, floorCode);
        }
        
        public BasicMvcApp.PrismaWCF.ActionEntity[] GetAllWORequestActions() {
            return base.Channel.GetAllWORequestActions();
        }
        
        public System.Threading.Tasks.Task<BasicMvcApp.PrismaWCF.ActionEntity[]> GetAllWORequestActionsAsync() {
            return base.Channel.GetAllWORequestActionsAsync();
        }
    }
}
