//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicWCFService.Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLroom
    {
        public string blbuilding_code { get; set; }
        public string blfloor_code { get; set; }
        public string blroom_code { get; set; }
        public string descr { get; set; }
        public string blstatus_code { get; set; }
        public Nullable<decimal> area { get; set; }
        public string blroomcls_code { get; set; }
        public string blroomclstype_code { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual BLfloor BLfloor { get; set; }
    }
}
