//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoToWin.Prisma.BasicWCFService.Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLzone
    {
        public BLzone()
        {
            this.BLbuilding = new HashSet<BLbuilding>();
        }
    
        public string blzone_code { get; set; }
        public string descr { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual ICollection<BLbuilding> BLbuilding { get; set; }
    }
}
