//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoToWin.Prisma.BasicWCFService.Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WOaction
    {
        public string woaction_code { get; set; }
        public string descr { get; set; }
        public string type { get; set; }
        public string wo { get; set; }
        public string da { get; set; }
        public string pa { get; set; }
        public string wr { get; set; }
        public string sa { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> hrs { get; set; }
        public Nullable<decimal> laborcost { get; set; }
        public Nullable<decimal> mtrlcost { get; set; }
        public Nullable<decimal> vendorcost { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
