//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicWCFService.Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WOrequest
    {
        public int worequest_code { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string createdby { get; set; }
        public string status { get; set; }
        public string blbuilding_code { get; set; }
        public string blfloor_code { get; set; }
        public string blroom_code { get; set; }
        public string ascatalog_code { get; set; }
        public string woaction_code { get; set; }
        public string descr { get; set; }
        public Nullable<int> wo_code { get; set; }
        public Nullable<int> partwo_code { get; set; }
        public string requestor { get; set; }
        public string reqphone { get; set; }
    }
}
